# Generated by Django 4.2 on 2023-08-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usernameController", models.EmailField(max_length=100, unique=True)),
                ("pwdController", models.CharField(max_length=80, unique=True)),
                ("role", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="outsiders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullnameController", models.CharField(max_length=100, unique=True)),
                ("phoneController", models.CharField(max_length=100)),
                ("emailController", models.EmailField(max_length=100, unique=True)),
                ("usernmController", models.CharField(max_length=100)),
                ("pwdController", models.CharField(max_length=80, unique=True)),
                ("role", models.CharField(max_length=10)),
                ("userstatus", models.CharField(max_length=10)),
                (
                    "userimage",
                    models.ImageField(
                        default="/meadia/images/user1.png",
                        max_length=500,
                        upload_to="images",
                    ),
                ),
                (
                    "log_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="Outsider.log"
                    ),
                ),
            ],
        ),
    ]
