# Generated by Django 4.2 on 2023-08-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Outsider", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="usernameController",
            new_name="usernmController",
        ),
    ]
