# Generated by Django 4.2 on 2023-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Outsider", "0002_rename_usernamecontroller_log_usernmcontroller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="usernmController",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
