# Generated by Django 4.2.4 on 2023-09-04 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0003_rename_pets_petdata"),
        ("Outsider", "0003_alter_log_usernmcontroller"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemname", models.CharField(max_length=500)),
                ("breedname", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images")),
                ("quantity", models.CharField(max_length=500)),
                ("total_price", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=10)),
                ("cart_status", models.CharField(max_length=10)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pet_Station.petdata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsider.outsiders",
                    ),
                ),
            ],
        ),
    ]
