# Generated by Django 4.2.4 on 2023-09-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0004_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.CharField(default="1", max_length=500),
        ),
    ]
