# Generated by Django 4.2.4 on 2023-09-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0005_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.CharField(max_length=500),
        ),
    ]
