# Generated by Django 4.2.4 on 2023-09-09 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0006_alter_cart_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("contact", models.CharField(max_length=500)),
                ("pincode", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=500)),
                ("state", models.CharField(max_length=500)),
                ("area", models.CharField(max_length=500)),
                ("buildingName", models.CharField(max_length=500)),
                (
                    "landmark",
                    models.CharField(default="No value", max_length=500, null=True),
                ),
                ("addressType", models.CharField(max_length=500)),
                ("orderAddressStatus", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsider.outsiders",
                    ),
                ),
            ],
        ),
    ]
