# Generated by Django 4.2.4 on 2023-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0007_orderaddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddress",
            name="landmark",
            field=models.CharField(
                blank=True, default="No value", max_length=500, null=True
            ),
        ),
    ]
