# Generated by Django 4.2.4 on 2023-09-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0008_alter_orderaddress_landmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
                ("reply", models.CharField(default="no reply", max_length=500)),
                ("chatstatus", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsider.outsiders",
                    ),
                ),
            ],
        ),
    ]
