# Generated by Django 4.2.4 on 2023-09-15 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0003_rename_pets_petdata"),
        ("Outsider", "0009_chat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=500)),
                ("image", models.ImageField(upload_to="images")),
                ("breed", models.CharField(max_length=500)),
                ("price", models.CharField(max_length=300)),
                ("favStatus", models.CharField(max_length=200)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pet_Station.petdata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsider.outsiders",
                    ),
                ),
            ],
        ),
    ]
