# Generated by Django 4.2.4 on 2023-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0011_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="expday",
            field=models.CharField(default="10", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="expday",
            field=models.CharField(default="10", max_length=100),
        ),
    ]
