# Generated by Django 4.2.4 on 2023-09-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0008_alter_food_benefit_alter_food_company_name_and_more"),
        ("Outsider", "0015_favorite_fooditem_alter_favorite_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fooditem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Pet_Station.food",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Pet_Station.petdata",
            ),
        ),
    ]
