# Generated by Django 4.2.4 on 2023-09-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0016_order_fooditem_alter_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.FloatField(),
        ),
    ]
