# Generated by Django 4.2 on 2023-08-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Pet_Station", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_image",
            field=models.ImageField(max_length=500, upload_to="images/"),
        ),
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("breed", models.CharField(max_length=200)),
                ("age", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("female", "Female"), ("male", "Male")], max_length=100
                    ),
                ),
                ("price", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=800)),
                ("rating", models.CharField(max_length=100, null=True)),
                (
                    "image1",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image2",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image3",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image4",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                ("petstatus", models.CharField(max_length=100)),
                (
                    "categoryId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pet_Station.categories",
                    ),
                ),
            ],
        ),
    ]
