# Generated by Django 4.2 on 2023-08-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Pet_Station", "0002_alter_categories_category_image_pets"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pets",
            new_name="PetData",
        ),
    ]
