# Generated by Django 4.2.4 on 2023-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0003_rename_pets_petdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="petdata",
            name="expdate",
            field=models.CharField(default="10", max_length=200),
        ),
    ]
