# Generated by Django 4.2.4 on 2023-09-18 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0004_petdata_expdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=200)),
                ("product_name", models.CharField(max_length=800)),
                ("product_type", models.CharField(max_length=500)),
                ("net_weight", models.CharField(max_length=400)),
                ("company_name", models.CharField(max_length=800)),
                ("benefit", models.CharField(max_length=800)),
                ("price", models.CharField(max_length=200)),
                ("marketed_by", models.CharField(max_length=800)),
                ("description", models.CharField(max_length=800)),
                ("expdate", models.CharField(max_length=200)),
                (
                    "image1",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image2",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image3",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image4",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                (
                    "image5",
                    models.ImageField(max_length=500, null=True, upload_to="images/"),
                ),
                ("rating", models.CharField(max_length=100, null=True)),
                ("foodstatus", models.CharField(max_length=100)),
                (
                    "categoryId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pet_Station.categories",
                    ),
                ),
            ],
        ),
    ]
