# Generated by Django 4.2.4 on 2023-09-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0005_food"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="rating",
            field=models.FloatField(default=0.0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="petdata",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("male", "Male"), ("pair", "Pair")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="petdata",
            name="rating",
            field=models.FloatField(default=0.0, max_length=100, null=True),
        ),
    ]
