# Generated by Django 4.2.4 on 2023-09-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0006_alter_food_rating_alter_petdata_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="rating_count",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="petdata",
            name="rating_count",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
