# Generated by Django 4.2.4 on 2023-09-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pet_Station", "0007_food_rating_count_petdata_rating_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="benefit",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="food",
            name="company_name",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="food",
            name="description",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="food",
            name="marketed_by",
            field=models.CharField(max_length=1800),
        ),
        migrations.AlterField(
            model_name="food",
            name="product_name",
            field=models.CharField(max_length=1100),
        ),
    ]
