# Generated by Django 4.2.4 on 2023-09-28 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0019_alter_payment_order"),
        ("Pet_Station", "0008_alter_food_benefit_alter_food_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_content", models.CharField(max_length=1800)),
                ("notification_title", models.CharField(max_length=800)),
                ("date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Outsider.outsiders",
                    ),
                ),
            ],
        ),
    ]
