# Generated by Django 4.2.4 on 2023-09-28 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Outsider", "0019_alter_payment_order"),
        ("Pet_Station", "0010_notification_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Notification",
            new_name="Notifications",
        ),
    ]
